# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kedify < Formula
  desc "Kedify CLI"
  homepage "https://github.com/kedify/cli"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kedify/cli/releases/download/v0.0.5/kedify_0.0.5_darwin_amd64.tar.gz"
      sha256 "ae41a894046dd7bc6a472bbdd037cb88f8602a42a9c50bd01859963311524344"

      define_method(:install) do
        bin.install "kedify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kedify/cli/releases/download/v0.0.5/kedify_0.0.5_darwin_arm64.tar.gz"
      sha256 "03d6a261f64c9306c15fa31b667678b1dcd55c761925c48a65ad15fff5eed6ce"

      define_method(:install) do
        bin.install "kedify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kedify/cli/releases/download/v0.0.5/kedify_0.0.5_linux_amd64.tar.gz"
      sha256 "6046a6323da55db72b1e7081f63fd27aed69dbc7a6f44565cb7e8f0b77b87618"
      define_method(:install) do
        bin.install "kedify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kedify/cli/releases/download/v0.0.5/kedify_0.0.5_linux_arm64.tar.gz"
      sha256 "5cdb718f0e088621a138ec6be68b9132c49a6694d81355dd07d4416d48cdf075"
      define_method(:install) do
        bin.install "kedify"
      end
    end
  end
end
