# This file was generated by GoReleaser. DO NOT EDIT.
cask "kedr" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "5b2f07c23ccba62135cf7f3fe82de552acfa601f2090282300b94d3fb2303a36"
      url "https://github.com/kedify/kedr/releases/download/v#{version}/kedr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1708c509a1f8481b7b0d64b2041a78b869050bc0a865e1fe2d35ad0565f47631"
      url "https://github.com/kedify/kedr/releases/download/v#{version}/kedr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ee1316a6b39154e73ba0064b3337d64213c1f2791eafe5a39135ebdbbbf369c"
      url "https://github.com/kedify/kedr/releases/download/v#{version}/kedr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1899b6f13d14971e179fb0308beff1d49bf52a5c095fd52600341ace75ee21b4"
      url "https://github.com/kedify/kedr/releases/download/v#{version}/kedr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kedr"
  desc "Kubernetes CPU and memory resource recommender"
  homepage "https://github.com/kedify/kedr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kedr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kedr"]
    end
  end

  # No zap stanza required
end
